#!/bin/bash

set -o nounset
set -o errexit

# Sort an input FASTA file by sequence name

WORKING_DIR=$1
HOST_WORKING_DIR=$2
FILE_NAME=$3
INPUT=$4
OUTPUT=$5

FILE_DIR=${WORKING_DIR}/cga_working_dir/${FILE_NAME}
HOST_FILE_DIR=${HOST_WORKING_DIR}/cga_working_dir/${FILE_NAME}

echo "3. Sorting by sequence names (${INPUT})"

rm -f ${FILE_DIR}/${OUTPUT}

docker run --rm \
	-v ${HOST_FILE_DIR}:/data \
	-v /var/run/docker.sock:/var/run/docker.sock \
	pegi3s/utilities:${version_utilities} \
		fasta_remove_line_breaks /data/${INPUT}

docker run --rm \
	-v ${HOST_FILE_DIR}:/data \
	-v /var/run/docker.sock:/var/run/docker.sock \
	pegi3s/utilities:${version_utilities} \
		fasta_sort_by_header /data/${INPUT} /data/${OUTPUT}
