#!/bin/bash

set -o nounset
set -o errexit

# Sort an input FASTA file by sequence name

INPUT=$1
OUTPUT=$2

echo "3. Sorting by sequence names (${INPUT})"

rm -f ${OUTPUT}

grep '>' ${INPUT} | sed 's/>//g' | sort -V > /tmp/tmp1
while read name; do
	grep -F -A1 "${name}" ${INPUT} >> ${OUTPUT}
done < /tmp/tmp1

rm /tmp/tmp1
