#!/bin/bash

set -o nounset
set -o errexit

# Script parameters are specified in the following environment 
# variables (set by Compi):
# 
# ${working_dir}
# ${host_working_dir}
# ${input_fasta}
# ${version_seqkit}
#

rm -rf ${working_dir}/cga_working_dir/*

docker run --rm -v ${host_working_dir}:/data \
	pegi3s/seqkit:${version_seqkit} split \
		--by-size 1 \
		/data/${input_fasta} \
		--out-dir /data/cga_working_dir/input_fasta_split

for FILE_NAME in $(ls ${working_dir}/cga_working_dir/input_fasta_split/); do
	mkdir -p ${working_dir}/cga_working_dir/${FILE_NAME}
	mv ${working_dir}/cga_working_dir/input_fasta_split/${FILE_NAME} ${working_dir}/cga_working_dir/${FILE_NAME}/00_${FILE_NAME}
done

rm -rf ${working_dir}/cga_working_dir/input_fasta_split/

ls ${working_dir}/cga_working_dir > /tmp/files

mv /tmp/files ${working_dir}/cga_working_dir/files
